#ifndef ROTATIONAL_PARAMETERS_SLOW_WHEEL
#define ROTATIONAL_PARAMETERS_SLOW_WHEEL 1
#endif
#ifndef ROTATIONAL_PARAMETERS_FAST_WHEEL
#define ROTATIONAL_PARAMETERS_FAST_WHEEL 5
#endif
#ifndef HIGH_PRIORITY
#define HIGH_PRIORITY 3
#endif
#ifndef MEDIUM_PRIORITY
#define MEDIUM_PRIORITY 2
#endif
#ifndef LOW_PRIORITY
#define LOW_PRIORITY 1
#endif
#ifndef NONE_PRIORITY
#define NONE_PRIORITY 0
#endif
#ifndef AVOIDANCE
#define AVOIDANCE 0
#endif
#ifndef SEARCHLINE
#define SEARCHLINE 1
#endif
#ifndef BLUETOOTH
#define BLUETOOTH 2
#endif

extern char flag_mode;